# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=6),
        ),
    ]
